/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aluraconverter;

import java.awt.Color;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author bryan
 */
public class mainView extends javax.swing.JFrame {
    int xMouse, yMouse;
    
    Hashtable  <Object, ImageIcon> mElementos;
    
    private final String[] monedas = Monedas.getValores();
    
    private final String[] banderas = { "/icons/estados-unidos.png", "/icons/brasil.png", "/icons/canada.png", "/icons/suiza.png", "/icons/china.png", 
                                    "/icons/union-europea.png", "/icons/hong-kong.png", "/icons/india.png", "/icons/japon.png",
                                    "/icons/corea-del-sur.png", "/icons/mexico.png", "/icons/rusia.png", "/icons/turquia.png", "/icons/union-europea.png" };
    private final String[] temps = Temperatura.getValores();
    private final String[] masas = Masa.getValores();
    private final String[] dist = Distancia.getValores();
    
    
    /**
     * Creates new form mainView
     */
    public mainView() {
        initComponents();
        this.setLocationRelativeTo(null);
        mElementos = new Hashtable<>();
        initCombos();
        ((AbstractDocument) fromTempText.getDocument()).setDocumentFilter(new NumberOnlyFilter());
    }
    
    private void initCombos() {
        for(int i = 0; i < monedas.length; i++){
             fromMonedaCombo.addItem(monedas[i]);
             toMonedaCombo.addItem(monedas[i]);
             mElementos.put(monedas[i], getIcono(banderas[i]));
        }
        
        jComboBoxRender mRender = new jComboBoxRender(mElementos);
        fromMonedaCombo.setRenderer(mRender);
        toMonedaCombo.setRenderer(mRender);
        toMonedaCombo.setSelectedIndex(1);
        Monedas.actulizarTasas();
        updateLabel.setText("Última actualizacion de tasas: " + Monedas.getFechaActualizacion());
        
        for(String t: temps){
            fromTempCombo.addItem(t);
            toTempCombo.addItem(t);
        }
        toTempCombo.setSelectedIndex(1);
        
        for(String t: masas){
            fromMasaCombo.addItem(t);
            toMasaCombo.addItem(t);
        }
        toMasaCombo.setSelectedIndex(1);
        
        for(String t: dist){
            fromDistanciaCombo.addItem(t);
            toDistanciaCombo.addItem(t);
        }
        toDistanciaCombo.setSelectedIndex(1);
    }
    
    public ImageIcon getIcono (String path){
        return new ImageIcon(getClass().getResource(path));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        minLabel = new javax.swing.JLabel();
        lateralPanel = new javax.swing.JPanel();
        logo1Label = new javax.swing.JLabel();
        monedaButton = new javax.swing.JPanel();
        monedasLabel = new javax.swing.JLabel();
        masaButton = new javax.swing.JPanel();
        masaLabel = new javax.swing.JLabel();
        distanciaButton = new javax.swing.JPanel();
        distanciaLabel = new javax.swing.JLabel();
        temperaturaButton = new javax.swing.JPanel();
        temperaturaLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        welcomePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        monedasPanel = new javax.swing.JPanel();
        fromMonedaCombo = new javax.swing.JComboBox<>();
        toMonedaCombo = new javax.swing.JComboBox<>();
        fromMonedaText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        toMonedaText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        updateLabel = new javax.swing.JLabel();
        convMonedaButton = new javax.swing.JLabel();
        masaPanel = new javax.swing.JPanel();
        toMasaCombo = new javax.swing.JComboBox<>();
        fromMasaText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        toMasaText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fromMasaCombo = new javax.swing.JComboBox<>();
        convMasaButton = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        distanciaPanel = new javax.swing.JPanel();
        toDistanciaCombo = new javax.swing.JComboBox<>();
        fromDistanciaText = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        toDistanciaText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fromDistanciaCombo = new javax.swing.JComboBox<>();
        convDistButton = new javax.swing.JLabel();
        temperaturaPanel = new javax.swing.JPanel();
        toTempCombo = new javax.swing.JComboBox<>();
        fromTempText = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        toTempText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fromTempCombo = new javax.swing.JComboBox<>();
        convTempButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alura Convertidor de unidades");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraPanel.setBackground(new java.awt.Color(5, 25, 51));
        barraPanel.setPreferredSize(new java.awt.Dimension(600, 20));
        barraPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraPanelMouseDragged(evt);
            }
        });
        barraPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraPanelMousePressed(evt);
            }
        });
        barraPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });
        barraPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 20, -1));

        minLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        minLabel.setForeground(new java.awt.Color(255, 255, 255));
        minLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minLabel.setText("_");
        minLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minLabelMouseExited(evt);
            }
        });
        barraPanel.add(minLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -10, 20, 30));

        getContentPane().add(barraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 20));

        lateralPanel.setBackground(new java.awt.Color(5, 25, 51));
        lateralPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/aluralogo.png"))); // NOI18N
        lateralPanel.add(logo1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 210, 140));

        monedaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        monedaButton.setOpaque(false);
        monedaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monedaButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monedaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                monedaButtonMouseExited(evt);
            }
        });
        monedaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monedasLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        monedasLabel.setForeground(new java.awt.Color(255, 255, 255));
        monedasLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        monedasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/intercambiar.png"))); // NOI18N
        monedasLabel.setText("Monedas");
        monedasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        monedaButton.add(monedasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, 50));

        lateralPanel.add(monedaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 50));

        masaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masaButton.setOpaque(false);
        masaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masaButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masaButtonMouseExited(evt);
            }
        });
        masaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masaLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        masaLabel.setForeground(new java.awt.Color(255, 255, 255));
        masaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        masaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bascula.png"))); // NOI18N
        masaLabel.setText("Masa");
        masaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masaButton.add(masaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, 50));

        lateralPanel.add(masaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 50));

        distanciaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        distanciaButton.setOpaque(false);
        distanciaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                distanciaButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                distanciaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                distanciaButtonMouseExited(evt);
            }
        });
        distanciaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        distanciaLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        distanciaLabel.setForeground(new java.awt.Color(255, 255, 255));
        distanciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        distanciaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/distancia.png"))); // NOI18N
        distanciaLabel.setText("Distancia");
        distanciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        distanciaButton.add(distanciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, 50));

        lateralPanel.add(distanciaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 50));

        temperaturaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        temperaturaButton.setOpaque(false);
        temperaturaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temperaturaButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                temperaturaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                temperaturaButtonMouseExited(evt);
            }
        });
        temperaturaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        temperaturaLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        temperaturaLabel.setForeground(new java.awt.Color(255, 255, 255));
        temperaturaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        temperaturaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/termometro.png"))); // NOI18N
        temperaturaLabel.setText("Temperatura");
        temperaturaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        temperaturaButton.add(temperaturaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, 50));

        lateralPanel.add(temperaturaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 210, 50));

        getContentPane().add(lateralPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 410));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        welcomePanel.setBackground(new java.awt.Color(250, 250, 250));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo.png"))); // NOI18N
        welcomePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 390, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("de unidades de Alura");
        welcomePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 390, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bienvenido al conversor");
        welcomePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 390, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Seleccione una opcíon para continuar");
        welcomePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 390, -1));

        jTabbedPane1.addTab("tab1", welcomePanel);

        monedasPanel.setBackground(new java.awt.Color(250, 250, 250));
        monedasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fromMonedaCombo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fromMonedaCombo.setMaximumRowCount(5);
        fromMonedaCombo.setBorder(null);
        fromMonedaCombo.setOpaque(true);
        monedasPanel.add(fromMonedaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 40));

        toMonedaCombo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        toMonedaCombo.setMaximumRowCount(5);
        toMonedaCombo.setBorder(null);
        monedasPanel.add(toMonedaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 110, 40));

        fromMonedaText.setBackground(new java.awt.Color(250, 250, 250));
        fromMonedaText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        fromMonedaText.setForeground(new java.awt.Color(128, 128, 128));
        fromMonedaText.setText("0.0");
        fromMonedaText.setBorder(null);
        fromMonedaText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fromMonedaTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fromMonedaTextFocusLost(evt);
            }
        });
        monedasPanel.add(fromMonedaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 30));

        jSeparator1.setForeground(new java.awt.Color(15, 83, 168));
        jSeparator1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        monedasPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 10));

        jSeparator2.setForeground(new java.awt.Color(15, 83, 168));
        jSeparator2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        monedasPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, 10));

        toMonedaText.setBackground(new java.awt.Color(250, 250, 250));
        toMonedaText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        toMonedaText.setForeground(new java.awt.Color(128, 128, 128));
        toMonedaText.setText("0.0");
        toMonedaText.setBorder(null);
        toMonedaText.setDisabledTextColor(new java.awt.Color(128, 128, 128));
        toMonedaText.setEnabled(false);
        monedasPanel.add(toMonedaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha-doble.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        monedasPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(15, 83, 168));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Conversor de monedas");
        monedasPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 390, 40));

        updateLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updateLabel.setForeground(new java.awt.Color(5, 25, 51));
        updateLabel.setText("Última actualizacion de tasas: ");
        monedasPanel.add(updateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 370, -1));

        convMonedaButton.setBackground(new java.awt.Color(5, 25, 51));
        convMonedaButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        convMonedaButton.setForeground(new java.awt.Color(255, 255, 255));
        convMonedaButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convMonedaButton.setText("Convertir");
        convMonedaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convMonedaButton.setOpaque(true);
        convMonedaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convMonedaButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convMonedaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convMonedaButtonMouseExited(evt);
            }
        });
        monedasPanel.add(convMonedaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, 30));

        jTabbedPane1.addTab("tab2", monedasPanel);

        masaPanel.setBackground(new java.awt.Color(250, 250, 250));
        masaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toMasaCombo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        toMasaCombo.setMaximumRowCount(5);
        toMasaCombo.setBorder(null);
        masaPanel.add(toMasaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 110, 40));

        fromMasaText.setBackground(new java.awt.Color(250, 250, 250));
        fromMasaText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        fromMasaText.setForeground(new java.awt.Color(128, 128, 128));
        fromMasaText.setText("0.0");
        fromMasaText.setBorder(null);
        fromMasaText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fromMasaTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fromMasaTextFocusLost(evt);
            }
        });
        masaPanel.add(fromMasaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 30));

        jSeparator3.setForeground(new java.awt.Color(15, 83, 168));
        jSeparator3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        masaPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 10));

        jSeparator4.setForeground(new java.awt.Color(15, 83, 168));
        jSeparator4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        masaPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, 10));

        toMasaText.setBackground(new java.awt.Color(250, 250, 250));
        toMasaText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        toMasaText.setForeground(new java.awt.Color(128, 128, 128));
        toMasaText.setText("0.0");
        toMasaText.setBorder(null);
        toMasaText.setDisabledTextColor(new java.awt.Color(128, 128, 128));
        toMasaText.setEnabled(false);
        masaPanel.add(toMasaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha-doble.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        masaPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(15, 83, 168));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("de masa");
        masaPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 390, 40));

        fromMasaCombo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fromMasaCombo.setMaximumRowCount(5);
        fromMasaCombo.setBorder(null);
        fromMasaCombo.setOpaque(true);
        masaPanel.add(fromMasaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 40));

        convMasaButton.setBackground(new java.awt.Color(5, 25, 51));
        convMasaButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        convMasaButton.setForeground(new java.awt.Color(255, 255, 255));
        convMasaButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convMasaButton.setText("Convertir");
        convMasaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convMasaButton.setOpaque(true);
        convMasaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convMasaButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convMasaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convMasaButtonMouseExited(evt);
            }
        });
        masaPanel.add(convMasaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, 30));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(15, 83, 168));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Conversor de unidades");
        masaPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 390, 40));

        jTabbedPane1.addTab("tab3", masaPanel);

        distanciaPanel.setBackground(new java.awt.Color(250, 250, 250));
        distanciaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toDistanciaCombo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        toDistanciaCombo.setMaximumRowCount(5);
        toDistanciaCombo.setBorder(null);
        distanciaPanel.add(toDistanciaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 110, 40));

        fromDistanciaText.setBackground(new java.awt.Color(250, 250, 250));
        fromDistanciaText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        fromDistanciaText.setForeground(new java.awt.Color(128, 128, 128));
        fromDistanciaText.setText("0.0");
        fromDistanciaText.setBorder(null);
        fromDistanciaText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fromDistanciaTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fromDistanciaTextFocusLost(evt);
            }
        });
        distanciaPanel.add(fromDistanciaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 30));

        jSeparator5.setForeground(new java.awt.Color(15, 83, 168));
        jSeparator5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        distanciaPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 10));

        jSeparator6.setForeground(new java.awt.Color(15, 83, 168));
        jSeparator6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        distanciaPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, 10));

        toDistanciaText.setBackground(new java.awt.Color(250, 250, 250));
        toDistanciaText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        toDistanciaText.setForeground(new java.awt.Color(128, 128, 128));
        toDistanciaText.setText("0.0");
        toDistanciaText.setBorder(null);
        toDistanciaText.setDisabledTextColor(new java.awt.Color(128, 128, 128));
        toDistanciaText.setEnabled(false);
        distanciaPanel.add(toDistanciaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha-doble.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        distanciaPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(15, 83, 168));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Conversor de distancias");
        distanciaPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 390, 40));

        fromDistanciaCombo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fromDistanciaCombo.setMaximumRowCount(5);
        fromDistanciaCombo.setBorder(null);
        fromDistanciaCombo.setOpaque(true);
        distanciaPanel.add(fromDistanciaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 40));

        convDistButton.setBackground(new java.awt.Color(5, 25, 51));
        convDistButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        convDistButton.setForeground(new java.awt.Color(255, 255, 255));
        convDistButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convDistButton.setText("Convertir");
        convDistButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convDistButton.setOpaque(true);
        convDistButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convDistButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convDistButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convDistButtonMouseExited(evt);
            }
        });
        distanciaPanel.add(convDistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, 30));

        jTabbedPane1.addTab("tab4", distanciaPanel);

        temperaturaPanel.setBackground(new java.awt.Color(250, 250, 250));
        temperaturaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toTempCombo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        toTempCombo.setMaximumRowCount(5);
        toTempCombo.setBorder(null);
        temperaturaPanel.add(toTempCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 110, 40));

        fromTempText.setBackground(new java.awt.Color(250, 250, 250));
        fromTempText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        fromTempText.setForeground(new java.awt.Color(128, 128, 128));
        fromTempText.setText("0.0");
        fromTempText.setBorder(null);
        fromTempText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fromTempTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fromTempTextFocusLost(evt);
            }
        });
        temperaturaPanel.add(fromTempText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 30));

        jSeparator7.setForeground(new java.awt.Color(15, 83, 168));
        jSeparator7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        temperaturaPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 10));

        jSeparator8.setForeground(new java.awt.Color(15, 83, 168));
        jSeparator8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        temperaturaPanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, 10));

        toTempText.setBackground(new java.awt.Color(250, 250, 250));
        toTempText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        toTempText.setForeground(new java.awt.Color(128, 128, 128));
        toTempText.setText("0.0");
        toTempText.setBorder(null);
        toTempText.setDisabledTextColor(new java.awt.Color(128, 128, 128));
        toTempText.setEnabled(false);
        temperaturaPanel.add(toTempText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha-doble.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        temperaturaPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(15, 83, 168));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Conversor de temperaturas");
        temperaturaPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 390, 40));

        fromTempCombo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fromTempCombo.setMaximumRowCount(5);
        fromTempCombo.setBorder(null);
        fromTempCombo.setOpaque(true);
        temperaturaPanel.add(fromTempCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 40));

        convTempButton.setBackground(new java.awt.Color(5, 25, 51));
        convTempButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        convTempButton.setForeground(new java.awt.Color(255, 255, 255));
        convTempButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convTempButton.setText("Convertir");
        convTempButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convTempButton.setOpaque(true);
        convTempButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convTempButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convTempButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convTempButtonMouseExited(evt);
            }
        });
        temperaturaPanel.add(convTempButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, 30));

        jTabbedPane1.addTab("tab5", temperaturaPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 450, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void minLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minLabelMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_minLabelMouseClicked

    private void minLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minLabelMouseEntered
        minLabel.setBackground(Color.blue);
        minLabel.setOpaque(true);
    }//GEN-LAST:event_minLabelMouseEntered

    private void minLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minLabelMouseExited
        minLabel.setBackground(Color.white);
        minLabel.setOpaque(false);
    }//GEN-LAST:event_minLabelMouseExited

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitLabel.setBackground(Color.red);
        exitLabel.setOpaque(true);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitLabel.setBackground(Color.white);
        exitLabel.setOpaque(false);
    }//GEN-LAST:event_exitLabelMouseExited

    private void monedaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaButtonMouseEntered
        monedaButton.setBackground(new Color(15, 83, 168));
        monedaButton.setOpaque(true);
    }//GEN-LAST:event_monedaButtonMouseEntered

    private void monedaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaButtonMouseExited
        monedaButton.setBackground(Color.white);
        monedaButton.setOpaque(false);
    }//GEN-LAST:event_monedaButtonMouseExited

    private void masaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaButtonMouseEntered
        masaButton.setBackground(new Color(15, 83, 168));
        masaButton.setOpaque(true);
    }//GEN-LAST:event_masaButtonMouseEntered

    private void masaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaButtonMouseExited
        masaButton.setBackground(Color.white);
        masaButton.setOpaque(false);
    }//GEN-LAST:event_masaButtonMouseExited

    private void distanciaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distanciaButtonMouseEntered
        distanciaButton.setBackground(new Color(15, 83, 168));
        distanciaButton.setOpaque(true);
    }//GEN-LAST:event_distanciaButtonMouseEntered

    private void distanciaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distanciaButtonMouseExited
        distanciaButton.setBackground(Color.white);
        distanciaButton.setOpaque(false);
    }//GEN-LAST:event_distanciaButtonMouseExited

    private void temperaturaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturaButtonMouseExited
        temperaturaButton.setBackground(Color.white);
        temperaturaButton.setOpaque(false);
    }//GEN-LAST:event_temperaturaButtonMouseExited

    private void temperaturaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturaButtonMouseEntered
        temperaturaButton.setBackground(new Color(15, 83, 168));
        temperaturaButton.setOpaque(true);
    }//GEN-LAST:event_temperaturaButtonMouseEntered

    private void barraPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraPanelMousePressed

    private void barraPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraPanelMouseDragged

    private void monedaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaButtonMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_monedaButtonMouseClicked

    private void masaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaButtonMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_masaButtonMouseClicked

    private void distanciaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distanciaButtonMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_distanciaButtonMouseClicked

    private void temperaturaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturaButtonMouseClicked
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_temperaturaButtonMouseClicked

    private Double convertirADouble(String text){
        return Double.valueOf(text);
    }
    private void fromMonedaTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromMonedaTextFocusGained
        if (fromMonedaText.getText().equals("0.0")) {
            fromMonedaText.setText("");
            fromMonedaText.setForeground(Color.black);
            toMonedaText.setText("");
            toMonedaText.setDisabledTextColor(Color.black);
        }
    }//GEN-LAST:event_fromMonedaTextFocusGained

    private void fromMonedaTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromMonedaTextFocusLost
        if (fromMonedaText.getText().equals("")) {
            fromMonedaText.setText("0.0");
            fromMonedaText.setForeground(Color.gray);
            toMonedaText.setText("0.0");
            toMonedaText.setDisabledTextColor(Color.gray);
        }
    }//GEN-LAST:event_fromMonedaTextFocusLost

    private void fromMasaTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromMasaTextFocusGained
        if (fromMasaText.getText().equals("0.0")) {
            fromMasaText.setText("");
            fromMasaText.setForeground(Color.black);
            toMasaText.setText("");
            toMasaText.setDisabledTextColor(Color.black);
        }
    }//GEN-LAST:event_fromMasaTextFocusGained

    private void fromMasaTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromMasaTextFocusLost
        if (fromMasaText.getText().equals("")) {
            fromMasaText.setText("0.0");
            fromMasaText.setForeground(Color.gray);
            toMasaText.setText("0.0");
            toMasaText.setDisabledTextColor(Color.gray);
        }
    }//GEN-LAST:event_fromMasaTextFocusLost

    private void fromDistanciaTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromDistanciaTextFocusGained
        if (fromDistanciaText.getText().equals("0.0")) {
            fromDistanciaText.setText("");
            fromDistanciaText.setForeground(Color.black);
            toDistanciaText.setText("");
            toDistanciaText.setDisabledTextColor(Color.black);
        }
    }//GEN-LAST:event_fromDistanciaTextFocusGained

    private void fromDistanciaTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromDistanciaTextFocusLost
        if (fromDistanciaText.getText().equals("")) {
            fromDistanciaText.setText("0.0");
            fromDistanciaText.setForeground(Color.gray);
            toDistanciaText.setText("0.0");
            toDistanciaText.setDisabledTextColor(Color.gray);
        }
    }//GEN-LAST:event_fromDistanciaTextFocusLost

    private void fromTempTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromTempTextFocusGained
        if (fromTempText.getText().equals("0.0")) {
            fromTempText.setText("");
            fromTempText.setForeground(Color.black);
            toTempText.setText("");
            toTempText.setDisabledTextColor(Color.black);
        }
    }//GEN-LAST:event_fromTempTextFocusGained

    private void fromTempTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromTempTextFocusLost
        if (fromTempText.getText().equals("")) {
            fromTempText.setText("0.0");
            fromTempText.setForeground(Color.gray);
            toTempText.setText("0.0");
            toTempText.setDisabledTextColor(Color.gray);
        }
    }//GEN-LAST:event_fromTempTextFocusLost

    private void convTempButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convTempButtonMouseClicked
        try {
            Double cantidad = convertirADouble(fromTempText.getText());
            toTempText.setText(String.valueOf(Temperatura.convertir(cantidad, 
                    (String)fromTempCombo.getSelectedItem(), (String)toTempCombo.getSelectedItem())));
            toTempText.setCaretPosition(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número valido");
        }
    }//GEN-LAST:event_convTempButtonMouseClicked

    private void convTempButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convTempButtonMouseEntered
        convTempButton.setBackground(new Color(25,45,71));
    }//GEN-LAST:event_convTempButtonMouseEntered

    private void convTempButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convTempButtonMouseExited
        convTempButton.setBackground(new Color(5,25,51));
    }//GEN-LAST:event_convTempButtonMouseExited

    private void convDistButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convDistButtonMouseClicked
        try {
            Double cantidad = convertirADouble(fromDistanciaText.getText());
            toDistanciaText.setText(String.valueOf(Distancia.convertir(cantidad, 
                    (String)fromDistanciaCombo.getSelectedItem(), (String)toDistanciaCombo.getSelectedItem())));
            toDistanciaText.setCaretPosition(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número valido");
        }
    }//GEN-LAST:event_convDistButtonMouseClicked

    private void convDistButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convDistButtonMouseEntered
        convDistButton.setBackground(new Color(25,45,71));
    }//GEN-LAST:event_convDistButtonMouseEntered

    private void convDistButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convDistButtonMouseExited
        convDistButton.setBackground(new Color(5,25,51));
    }//GEN-LAST:event_convDistButtonMouseExited

    private void convMasaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMasaButtonMouseClicked
        try {
            Double cantidad = convertirADouble(fromMasaText.getText());
            toMasaText.setText(String.valueOf(Masa.convertir(cantidad, 
                    (String)fromMasaCombo.getSelectedItem(), (String)toMasaCombo.getSelectedItem())));
            toMasaText.setCaretPosition(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número valido");
        }
    }//GEN-LAST:event_convMasaButtonMouseClicked

    private void convMasaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMasaButtonMouseEntered
        convMasaButton.setBackground(new Color(25,45,71));
    }//GEN-LAST:event_convMasaButtonMouseEntered

    private void convMasaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMasaButtonMouseExited
        convMasaButton.setBackground(new Color(5,25,51));
    }//GEN-LAST:event_convMasaButtonMouseExited

    private void convMonedaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMonedaButtonMouseClicked
        try {
            Double cantidad = convertirADouble(fromMonedaText.getText());
            toMonedaText.setText(String.valueOf(Monedas.convertir(cantidad, 
                    (String)fromMonedaCombo.getSelectedItem(), (String)toMonedaCombo.getSelectedItem())));
            toMonedaText.setCaretPosition(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Debe ingresar un número valido");
        }
    }//GEN-LAST:event_convMonedaButtonMouseClicked

    private void convMonedaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMonedaButtonMouseEntered
        convMonedaButton.setBackground(new Color(25,45,71));
    }//GEN-LAST:event_convMonedaButtonMouseEntered

    private void convMonedaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMonedaButtonMouseExited
        convMonedaButton.setBackground(new Color(5,25,51));
    }//GEN-LAST:event_convMonedaButtonMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int index = fromMonedaCombo.getSelectedIndex();
        fromMonedaCombo.setSelectedIndex(toMonedaCombo.getSelectedIndex());
        toMonedaCombo.setSelectedIndex(index);
        String texto = fromMonedaText.getText();
        fromMonedaText.setText(toMonedaText.getText());
        toMonedaText.setText(texto);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int index = fromMasaCombo.getSelectedIndex();
        fromMasaCombo.setSelectedIndex(toMasaCombo.getSelectedIndex());
        toMasaCombo.setSelectedIndex(index);
        String texto = fromMasaText.getText();
        fromMasaText.setText(toMasaText.getText());
        toMasaText.setText(texto);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int index = fromDistanciaCombo.getSelectedIndex();
        fromDistanciaCombo.setSelectedIndex(toDistanciaCombo.getSelectedIndex());
        toDistanciaCombo.setSelectedIndex(index);
        String texto = fromDistanciaText.getText();
        fromDistanciaText.setText(toDistanciaText.getText());
        toDistanciaText.setText(texto);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int index = fromTempCombo.getSelectedIndex();
        fromTempCombo.setSelectedIndex(toTempCombo.getSelectedIndex());
        toTempCombo.setSelectedIndex(index);
        String texto = fromTempText.getText();
        fromTempText.setText(toTempText.getText());
        toTempText.setText(texto);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new mainView().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraPanel;
    private javax.swing.JLabel convDistButton;
    private javax.swing.JLabel convMasaButton;
    private javax.swing.JLabel convMonedaButton;
    private javax.swing.JLabel convTempButton;
    private javax.swing.JPanel distanciaButton;
    private javax.swing.JLabel distanciaLabel;
    private javax.swing.JPanel distanciaPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JComboBox<String> fromDistanciaCombo;
    private javax.swing.JTextField fromDistanciaText;
    private javax.swing.JComboBox<String> fromMasaCombo;
    private javax.swing.JTextField fromMasaText;
    private javax.swing.JComboBox<String> fromMonedaCombo;
    private javax.swing.JTextField fromMonedaText;
    private javax.swing.JComboBox<String> fromTempCombo;
    private javax.swing.JTextField fromTempText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel lateralPanel;
    private javax.swing.JLabel logo1Label;
    private javax.swing.JPanel masaButton;
    private javax.swing.JLabel masaLabel;
    private javax.swing.JPanel masaPanel;
    private javax.swing.JLabel minLabel;
    private javax.swing.JPanel monedaButton;
    private javax.swing.JLabel monedasLabel;
    private javax.swing.JPanel monedasPanel;
    private javax.swing.JPanel temperaturaButton;
    private javax.swing.JLabel temperaturaLabel;
    private javax.swing.JPanel temperaturaPanel;
    private javax.swing.JComboBox<String> toDistanciaCombo;
    private javax.swing.JTextField toDistanciaText;
    private javax.swing.JComboBox<String> toMasaCombo;
    private javax.swing.JTextField toMasaText;
    private javax.swing.JComboBox<String> toMonedaCombo;
    private javax.swing.JTextField toMonedaText;
    private javax.swing.JComboBox<String> toTempCombo;
    private javax.swing.JTextField toTempText;
    private javax.swing.JLabel updateLabel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables

}
